# markdownlint configuration
# Documentation: https://github.com/DavidAnson/markdownlint

# Default state for all rules
default: true

# MD001 - Heading levels should only increment by one level at a time
MD001: true

# MD003 - Heading style (prefer ATX style: # Heading)
MD003:
  style: atx

# MD004 - Unordered list style (prefer dash)
MD004:
  style: dash

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD009 - Trailing spaces (allow for line breaks)
MD009:
  br_spaces: 2

# MD010 - Hard tabs (not allowed)
MD010: true

# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013 - Line length (disabled - handled elsewhere)
MD013: false

# MD014 - Dollar signs used before commands without showing output
MD014: false

# MD022 - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024 - Multiple headings with the same content (allow for different sections)
MD024:
  siblings_only: true

# MD025 - Single title/top level heading
MD025: true

# MD026 - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!。，；：！"

# MD029 - Ordered list item prefix (disabled - lists intentionally continue after code blocks)
MD029: false

# MD030 - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD031 - Fenced code blocks should be surrounded by blank lines
MD031: true

# MD032 - Lists should be surrounded by blank lines
MD032: true

# MD033 - Inline HTML (allow specific elements)
MD033:
  allowed_elements:
    - br
    - sub
    - sup
    - kbd
    - details
    - summary

# MD034 - Bare URLs
MD034: false

# MD035 - Horizontal rule style
MD035:
  style: "---"

# MD036 - Emphasis used instead of a heading
MD036: false

# MD037 - Spaces inside emphasis markers
MD037: true

# MD038 - Spaces inside code span elements
MD038: true

# MD039 - Spaces inside link text
MD039: true

# MD040 - Fenced code blocks should have a language specified
MD040: false

# MD041 - First line in file should be a top level heading
MD041: false

# MD042 - No empty links
MD042: true

# MD044 - Proper names should have the correct capitalization
MD044: false

# MD045 - Images should have alt text
MD045: false

# MD046 - Code block style
MD046:
  style: fenced

# MD047 - Files should end with a single newline character
MD047: true

# MD048 - Code fence style
MD048:
  style: backtick

# MD049 - Emphasis style should be consistent
MD049:
  style: asterisk

# MD050 - Strong style should be consistent
MD050:
  style: asterisk
